parameters:
    genj_social_feed.api.twitter.class: 'Genj\SocialFeedBundle\Api\TwitterApi'
    genj_social_feed.api.facebook.class: 'Genj\SocialFeedBundle\Api\FacebookApi'
    genj_social_feed.api.instagram.class: 'Genj\SocialFeedBundle\Api\InstagramApi'
    genj_social_feed.entity.post.class: 'Genj\SocialFeedBundle\Entity\Post'
    genj_social_feed.entity.post_repository.class: 'Genj\SocialFeedBundle\Entity\PostRepository'

services:
    genj_social_feed.api.twitter:
        class: '%genj_social_feed.api.twitter.class%'
        arguments: ['%genj_social_feed.oauth%']

    genj_social_feed.api.facebook:
        class: '%genj_social_feed.api.facebook.class%'
        arguments: ['%genj_social_feed.oauth%']

    genj_social_feed.api.instagram:
        class: '%genj_social_feed.api.instagram.class%'
        arguments: ['%genj_social_feed.oauth%']

    genj_social_feed.entity.post_repository:
        factory: ['@doctrine', 'getRepository']
        class: '%genj_social_feed.entity.post_repository.class%'
        arguments: ['%genj_social_feed.entity.post.class%']